name: CI/CD Deployment

on:
  push:
    branches:
      - main # Deploy only when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      # Build the frontend
      - name: Build Frontend
        run: |
          cd frontend
          CI=false npm run build

      # Add EC2 server to known_hosts
      - name: Add host to known_hosts
        run: |
          run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Deploy to EC2
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          # Define directories
          FRONTEND_DIR=/var/www/frontend
          BACKEND_DIR=/var/www/backend

          # Clean up old files
          ssh -i "${{ env.KEY }}" ${{ env.USER }}@${{ env.HOST }} "rm -rf $FRONTEND_DIR/* $BACKEND_DIR/* && mkdir -p $FRONTEND_DIR $BACKEND_DIR"

          # Upload frontend build
          scp -i "${{ env.KEY }}" -r frontend/build/* ${{ env.USER }}@${{ env.HOST }}:$FRONTEND_DIR

          # Upload backend files
          scp -i "${{ env.KEY }}" -r backend/* ${{ env.USER }}@${{ env.HOST }}:$BACKEND_DIR

          # Restart backend
          ssh -i "${{ env.KEY }}" ${{ env.USER }}@${{ env.HOST }} "cd $BACKEND_DIR && npm install && pm2 reload ecosystem.config.js --update-env"
